apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kobo-frontend
spec:
  ingressClassName: traefik
  rules:
    - host: app-dev.kobo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kobo-frontend
                port:
                  number: 80
