apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kobo-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  tls:
    - hosts:
        - app-dev.kobo.79.137.32.27.nip.io
      secretName: app-dev-kobo-tls
  rules:
    - host: app-dev.kobo.79.137.32.27.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kobo-frontend
                port:
                  number: 80
