apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobo-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kobo-frontend
          image: ghcr.io/eliote-geeks/kobo-frontend:dev-latest
